### ISSUE TITLE
Restructure/plugin interface discussion

### ISSUE THREAD

**Issue by klauspost** [abrander/agento#1]
Looking at the current structure, it would perhaps ease the future development process to make some simple changes.
# Overall
- ~~Move client to main folder (so agento is buildable with a simple `go get`).~~ (second thought no - we would have two package names.
- Move data collection to a system specific folder.
- Make all data collection register itself in init().
- All data collection plugins must satisfy a simple interface to get a reading.
# Server
- Isn't "server" more of a proxy. Forwarding json data to influx?
- Beside potential data cleaning, is there a reason for the server to unmarshal to `agento.MachineStats`. Would it make sense to simply keep it as map[string]interface{} and just blindly forward whatever data it gets?
# Agento package

As mentioned everything currently in the package is moved to a `agento/linux` package.

The following is then the only exported functions in the `agento` package:

``` Go
type Plugin interface {
    // Gather the information.
    Gather() error

   // Return the latest reading.
    Map() map[string]interface{}

    // Doc - not sure if needed?
    Doc(map[string]string)
}

// Register a plugin.
func Register(name string,p Plugin) {
  ....
}
```

A plugin would then look like this:

``` Go
func init() {
  agento.Register("Dickstats", new(DiskStats))
}

// Diskstat is self-contained. This isn't required, but Gather() needs 
// to update the internal stats there is no need for it not to do so
type DiskStats struct {
    sampletime time.Time
    Disks      map[string]*SingleDiskStats `json:"disks"`

        // Diskstats now keeps track of its own history
    last      map[string]*SingleDiskStats
    lastSample time.Time
}

// func GetDiskStats() *DiskStats { is now changed to update itself.
func (d *DiskStats) Gather()  error {
    d.last = d.Disks
    d.Disks = make(map[string]*SingleDiskStats)
    ...
}
// The rest of the functions are adjusted to reflect the new place of
// the previous data, otherwise pretty much remain the same.
```

Adding a package with any number of plugins can now be done with a `import _ "github.com/abrander/agento/linux"`, etc. That will make it very easy to add arbitrary plugins, and plugins can be done any way that makes sense for them.

The main thing is that the agento (and subsequent server) doesn't know anything about what it will receive. It is simply an arbitrary map[string]interface{} that can be JSON marshalled.

Does that make any kind of sense?

**Comment by klauspost** [comment]
# Questions
- What if a plugin fails?
- Should the collector be able to re-start a plugin? Could be done with a `func Register(name string,newFn func() Plugin)`, so newFn() returns a new instance of the plugin.

**Comment by klauspost** [comment]
ok, I tried to make a main gather function. Except for logging, this is what it could look like:

``` Go
package agento

import (
    "os"
    "sync"
    "time"
)

type Plugin interface {
    // Return the name of the plugin
    Name() string

    // Gather the information.
    Gather() error

    // Return the latest reading.
    Map() map[string]interface{}

    // Doc - not sure if needed?
    Doc(map[string]string)
}

var plugins []Plugin

// Register a plugin
func Register(p Plugin) {
    plugins = append(plugins, p)
}

type Stats struct {
    Hostname       string                 `json:"h"`
    GatherDuration time.Duration          `json:"g"`
    StartTime      time.Time              `json:"at"`
    Readings       map[string]interface{} `json:"r"`
}

func Gather() *Stats {
    var s Stats
    var wg sync.WaitGroup
    var results = make(chan Plugin, len(plugins))
    s.StartTime = time.Now()
    s.Hostname, _ = os.Hostname()

    // Gather from all plugins
    wg.Add(len(plugins))
    for _, p := range plugins {
        go func(p Plugin) {
            defer wg.Done()
            err := p.Gather()
            if err != nil {
                return
            }
            results <- p
        }(p)
    }
    wg.Wait()
    s.GatherDuration = time.Since(s.StartTime)
    close(results)

    // Merge results
    for r := range results {
        m := r.Map()
        for k, v := range m {
            _, ok := s.Readings[k]
            if ok {
                LogWarning("Duplicate key %s. Second one from %s", k, r.Name())
            }
            s.Readings[k] = v
        }
    }

    return &s
}
```

`Gather()` is separate from `Map()`, so it is as lightweight as possible. We run them concurrently to potentially get readings as close to "the same time" as possible.

**Comment by abrander** [comment]
Thanks for commenting. I'll try to answer as good as I can :-)

> Move data collection to a system specific folder.

Makes much sense. Would also signal that we welcome support for additional operating systems.

> Make all data collection register itself in init().
> All data collection plugins must satisfy a simple interface to get a reading.
> Yes please, but I think that all collectors must marshall to some form of highly compressed JSON. See below.
> 
> Isn't "server" more of a proxy. Forwarding json data to influx?

For now it's pretty much just a "transcoding proxy", but it will have to do more. Authentication for one. I have been thinking about doing authentication like [Puppet](http://docs.puppetlabs.com/background/ssl/) or [etcd](https://github.com/coreos/etcd/blob/master/Documentation/security.md).

> Beside potential data cleaning, is there a reason for the server to unmarshal to agento.MachineStats. Would it make sense to simply keep it as map[string]interface{} and just blindly forward whatever data it gets?

There's at least two reasons for this:
- Data compression. The client->server JSON is very minimal. Server->influxdb is huge. We can further compress client->server JSON by omitting values that hasn't changed if we keep the update cycle as _one_ tick.
- Compatibility. It would not be desirable if all client must be updates because of a schema change.

I have thought about adding a [string]interface{} part of the client->server JSON for user supplied data, but for now have decided against it because there's plenty of software collecting arbitrary user supplied metrics.

As I side note: Agento started life as an agent collecting metrics directly to Influxdb, but it quickly became desirable to have a server part too.

> ok, I tried to make a main gather function. Except for logging, this is what it could look like:

I think Map() belong on the server side. Doc() is to have gatherers be self documenting, it's not needed, but it's very convenient.

I'm not sure it's wise to run all gatherers in parallel, we have to disturb the system we're measuring as little as possible. The current set of gatherers completes in under 2ms on a slow Digital Ocean guest.

Here's an example from `GetLoadStats()` where we try to remove ourselves from the equation:

```
// We don't want yo count ourself as active. We're sneeky.
stat.ActiveTasks -= 1
```

Let me know what you think.

**Comment by klauspost** [comment]
Good stuff. The most important part is the transport, so I'll focus on that.

# Pros of "typed" transfer:
- Assumptions about the data can be made. No need to transfer "disk name" for every reading of a disk, eg.
- No value = Previous value is much easier.
- Shorthand key names "u": value, instead of "du.sda.Used": value.
- Value types are preserved int remains an int and will not be converted to float64
- "Old types" are automatically dropped, so if "Dist"

# Pros of map[string]interface{} transfer
- Can transfer any value (other OS types, metrics from databases, etc)
- No need to keep server and client in sync.
- Possible to differentiate metric sampling rate (measure disk usage every 10 seconds, etc)
- Easy to write clients in other languages, since server doesn't need to know data types.
- Need to validate that types doesn't change (or just let influx do that).

The "new value = old value if omitted" can also be done with map[string]interface{}, so we can go for either solution if we want that. That will of course also mean that differentiated sampling rates isn't possible, since I don't assume we want datapoints in the DB, where the system wasn't measured.

I don't think that the gain of shorthand key names will really make that much of a difference, if we apply a deflate/gzip to the data.

If exact value types (int vs float mainly) are important, we could consider using bson, which is both more compact and preserves types. The only downside is that it may make it more difficult to write clients in other languages, since bson isn't as widely used as json.

> Compatibility. It would not be desirable if all client must be updates because of a schema change.

Do you really get this advantage in any of the methods? If you need to change a data type you would have to update both (at the same time), or have conversion code on the server. Granted this is much easier with static data than an `if regexMatch(key, "cpu\.[0-9]\.User") ....`

If you change `cpu.<n>.Frequency` from kHz to Hz (would be stupid I know) the a server change itself doesn't really help you much under any circumstance, since you have to change the client (and transfer) as well to indicate if it transmits kHz or Hz.

**Comment by abrander** [comment]
I don't think "foreign" clients are something we should strive to support. There's lots of software doing exactly that. Agento aims to do system data collection.

The pros as I see it:

## Pros of typed JSON transfer:
- Easy debugging.
- No need to keep client and database schema in sync.
- Shorthand key names "u": value, instead of "du.sda.Used": value.
- Value types are preserved int remains an int and will not be converted to float64.
- Can easily support non-numeric values (kernel version changes, package changes, events)

## Pros of map[string]interface{} transfer:
- Can transfer any value (other OS types, metrics from databases, etc)
- Easy to write clients in other languages, since server doesn't need to know data types.

I think we can differentiate the sample rate in any scheme, and I think we will have to. The current metrics gathered are almost free, but one can image collecting data that will require more of the client OS/services.

**Comment by abrander** [comment]
I think the most important part is the overall structure of the code base. Define an interface for gatherers and making sure it's easy to add additional gatherers. We need a simple way of adding new gatherers without much work and without the client->server payload exploding.

It would also be nice to be able to do `go get github.com/abrander/agento` and compile. You cannot do that now.

**Comment by klauspost** [comment]
> I don't think "foreign" clients are something we should strive to support.

ok, so this is an end-to-end system stats, but what if I want to add metrics like database queries/writes, etc - do I switch to something else, or wait for first party support?

**Comment by abrander** [comment]
> ok, so this is an end-to-end system stats, but what if I want to add metrics like database queries/writes, etc - do I switch to something else, or wait for first party support?

I see Agento as a better Munin. Mainly system statistics or data provided by simple vendor or 3rd party plugins. Not trying to replace anything. Fill the void in InfluxDB-land that is system metrics collection. Maybe it will make sense to support more use cases thou, I don't know.

I would love a plugin architecture that didn't require a rebuilding agento-client for adding a plugin and wasn't a fork bomb like many of Munins bash-based plugins. (Funny sidenote: If you graph a system running Munin with Agento, you can clearly see the spikes when Munin is collecting)

I have been thinking about the possibility of adding a javascript host to agento-client to enable Javascript-based plugins, but I'm not sure it's really usable or doable.

So to answer your question:
1) It could be feasible to report directly to InfluxDB using its graphite listener, or
2) You could wait (and hope) for native support for your specific metric, or
3) Roll your own plugin if that becomes possible.

**Comment by abrander** [comment]
I think we can safely close this by now - some ideas are implemented, some are not. If anyone would like to dig deeper, they may reopen.
